apiVersion: v1
kind: Secret
metadata:
  name: sizewise-database-secrets
  namespace: sizewise-suite
  labels:
    app: sizewise-suite
    component: database
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  POSTGRES_USER: c2l6ZXdpc2VfdXNlcg==  # sizewise_user
  POSTGRES_PASSWORD: c2l6ZXdpc2VfcGFzc3dvcmQ=  # sizewise_password

  # MongoDB credentials (base64 encoded)
  MONGODB_USERNAME: c2l6ZXdpc2VfbW9uZ28=  # sizewise_mongo
  MONGODB_PASSWORD: bW9uZ29fcGFzc3dvcmQ=  # mongo_password

  # Redis password (base64 encoded)
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # redis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: sizewise-app-secrets
  namespace: sizewise-suite
  labels:
    app: sizewise-suite
    component: application
type: Opaque
data:
  # Flask secret key (base64 encoded)
  FLASK_SECRET_KEY: Zmxhc2tfc3VwZXJfc2VjcmV0X2tleV9mb3Jfc2l6ZXdpc2Vfc3VpdGU=

  # JWT secret key (base64 encoded)
  JWT_SECRET_KEY: and0X3NlY3JldF9rZXlfZm9yX3NpemV3aXNlX2p3dF90b2tlbnM=

  # API keys (base64 encoded)
  EXTERNAL_API_KEY: ZXh0ZXJuYWxfYXBpX2tleV9mb3Jfc2l6ZXdpc2U=
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfZm9yX3NpemV3aXNlX2RhdGE=
---
apiVersion: v1
kind: Secret
metadata:
  name: sizewise-tls-secrets
  namespace: sizewise-suite
  labels:
    app: sizewise-suite
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key for HTTPS (base64 encoded)
  # These should be replaced with actual certificates in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
---
apiVersion: v1
kind: Secret
metadata:
  name: sizewise-service-mesh-ca
  namespace: sizewise-suite
  labels:
    app: sizewise-suite
    component: service-mesh
type: Opaque
data:
  # Service mesh CA certificate and key (base64 encoded)
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  ca.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
---
apiVersion: v1
kind: Secret
metadata:
  name: sizewise-monitoring-secrets
  namespace: sizewise-suite
  labels:
    app: sizewise-suite
    component: monitoring
type: Opaque
data:
  # Monitoring credentials (base64 encoded)
  PROMETHEUS_USERNAME: cHJvbWV0aGV1cw==  # prometheus
  PROMETHEUS_PASSWORD: cHJvbWV0aGV1c19wYXNzd29yZA==  # prometheus_password
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==  # grafana_admin_password