name: E2E Auth Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium webkit msedge

      - name: Run Playwright auth suite (Chromium + WebKit + Edge)
        env:
          NEXT_PUBLIC_ENABLE_OFFLINE_AUTH: "false"
          NEXT_PUBLIC_SENTRY_ENVIRONMENT: "ci"
          NEXT_PUBLIC_SENTRY_RELEASE: ${{ github.sha }}
        run: |
          npx playwright test e2e/01-authentication-flow-testing.spec.ts \
            --project=chromium --project=webkit --project="Microsoft Edge" \
            --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          retention-days: 7

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: frontend/test-results/**/trace.zip
          retention-days: 7

      - name: Upload Playwright screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-media
          path: |
            frontend/test-results/**/screenshot-*.png
            frontend/test-results/**/*.webm
          retention-days: 7
